In [1]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
#creating an array 
#Ex1) 
arr = np.array([1,4,6])
arr
type(arr)

numpy.ndarray

In [9]:
#to get dimention
arr.shape

(3,)

In [10]:
arr.dtype

dtype('int32')

In [11]:
#Ex2) 2d array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
type(arr2)

numpy.ndarray

In [13]:
arr2.shape

(3, 3)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
# arange() is similar to range()
np_arr1 = np.arange(10)
np_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np_arr2 = np_arr1 + 2
np_arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
# Performance measurement : %timeit is an python function, 
# which can be used to check the time taken by a particular piece of code
%timeit [i**3 for i in range(10000)]   #normal list

6.69 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit np.arange(10000)**3  #using numpy

79.1 µs ± 31.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
# Creating Numpy arrays
#Ex 1)
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [20]:
#Ex 2)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [21]:
np.arange(21,0,-2)

array([21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [22]:
np.zeros((3, 3))  #np.zeros(shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros(1, dtype=np.int32) #vector

array([0])

In [24]:
np.zeros((1,1), dtype=np.int32) #matrix

array([[0]])

In [25]:
#np.ones_like(ndarray)
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [26]:
#np.full(shape,value)
np.full((5, 3), 3.3)

array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [27]:
#np.eye(m) : this method is used to create identity matrix , here m = n
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#np.diag(list) : is used to create diagonal matrix
np.diag([2, 5, 68, 78])

array([[ 2,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 68,  0],
       [ 0,  0,  0, 78]])

In [29]:
# 1D array
a = np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [30]:
a[4]

10

In [31]:
# to get all the alternate elements
a[::2]

array([ 2,  6, 10, 14])

In [32]:
# consider we have 2D array
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
a[2,2]

10

In [35]:
a>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
# to get the elements between 5 to 10
a[(a > 5) & (a < 10)]

array([6, 7, 8, 9])

In [37]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
b = a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#shares_memory() : this method checks if both the arrays shares the same memory
np.shares_memory(a,b)

True

In [40]:
print(np.random.random())

0.14654256720764314


In [41]:
# you can specify the shape
x = np.random.random((4, 4))
x

array([[0.17088629, 0.90040491, 0.57950684, 0.14814399],
       [0.83334876, 0.5039406 , 0.71501121, 0.10845313],
       [0.80978705, 0.0338903 , 0.37679738, 0.86719732],
       [0.00822809, 0.26671802, 0.07452135, 0.86041628]])

In [42]:
num = np.random.randint(low = 20, high =100)
num

40

In [43]:
num = np.random.randint(low = 20, high =100,size = 5)
num

array([92, 59, 57, 57, 24])

In [44]:
# np.random.choice(list_of_choice,num_of_ele)
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [45]:
x = np.random.random((4, 4))
x

array([[0.64948032, 0.5038898 , 0.65489512, 0.03125012],
       [0.82317875, 0.26448628, 0.85351486, 0.32395217],
       [0.46305764, 0.5206038 , 0.42366519, 0.07556164],
       [0.13173007, 0.36836037, 0.49442943, 0.52881549]])

In [46]:
#np.round() : rounds an array to given number of decimals
rounded = np.round(x, 3)
rounded

array([[0.649, 0.504, 0.655, 0.031],
       [0.823, 0.264, 0.854, 0.324],
       [0.463, 0.521, 0.424, 0.076],
       [0.132, 0.368, 0.494, 0.529]])

In [47]:
new = rounded * 100
new

array([[64.9, 50.4, 65.5,  3.1],
       [82.3, 26.4, 85.4, 32.4],
       [46.3, 52.1, 42.4,  7.6],
       [13.2, 36.8, 49.4, 52.9]])

In [48]:
#astype() : to change the data type of elements
intt = new.astype(int)
intt

array([[64, 50, 65,  3],
       [82, 26, 85, 32],
       [46, 52, 42,  7],
       [13, 36, 49, 52]])

In [49]:
# reshape() :to reshape an array.
x = np.arange(32)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [50]:
x = x.reshape(4,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [51]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#np.sin()
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [53]:
#to get the exponential values i,e., e^num
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
np.sum(a)

45

In [55]:
a.max()

9

In [56]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])